### PR TITLE
Fix a bug when the Zabbix server response doesn't contain semicolon

### PR DESCRIPTION
**Pull request by davmrtl**

### CODE REVIEW

**Comment by davmrtl** [comment]
Any news on that pull request?

**Comment by untergeek** [comment]
Sorry for the delay.  We've been out of the country for an all-hands team meeting, and playing catchup ever since.  I'm looking at it now.

**Comment by untergeek** [comment]
@davmrtl I should mention that this change will not be published to RubyGems until Logstash 2.0 is released (with in the next 2 weeks, if the schedule holds)

**Comment by davmrtl** [comment]
No problem, thank you!

**Pull request merged**
